rcweb/importinfo/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from importinfo import views
from importinfo.models import BaseInfo, BaseInfoImporterModel
from django.contrib.auth.views import login, logout

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', login),
    url(r'^logout/$', logout),
    url(r'^register/$', views.register, name='register'),
    url(r'^create/$', views.BaseInfoCreateView.as_view(), name="create_base"),
    url(r'^import/$', views.import_create_view.as_view(), name="import"),
    url(r'^list_base/$', views.BaseInfoListView.as_view(), name='list_base'),
#    url(r'^uploadbureau/(?P<custid>[-_\w]+)/$',views.upload_bureau_view.as_view(), name='uploadbureau'),
    url(r'^detail_base/(?P<cust>[-_\w]+)/$', views.BaseInfoDetailView.as_view(), name = 'detail_base'),
)

rcweb/rcweb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rcweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^importinfo/', include('importinfo.urls', namespace="importinfo")),
    url(r'^admin/', include(admin.site.urls)),
)

rcweb/importinfo/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.db import models
from data_importer.importers import XLSXImporter
from django.utils import timezone
from django.contrib.auth.models import User
from crum import get_current_user

class BaseInfo(models.Model):
    EDUCATION_CHOICE = (('初中及以下','初中及以下'),('中专','中专'),('大专','大专'),('大学','大学'),('研究生','研究生'),
                        ('博士及以上','博士及以上'),('其他','其他'))
    VEHICLE_CHOICE = (('0','无'),('1','有'))
    MARRIAGE_CHOICE = (('未婚','未婚'),('已婚','已婚'),('离异','离异'),('丧偶','丧偶'),('其他','其他'))
    PROPERTY_CHOICE = (('无房','无房'),('有房有贷款','有房有贷款'),('有房无贷款','有房无贷款'))
    NATURE_CHOICE = (('其他','其他'),('三资','三资'),('民资','民资'),('国企','国企'),('机关','机关'),('外资','外资'))
    POSITION_CHOICE = (('其他','其他'),('非正式员工','非正式员工'),('正式员工','正式员工'),('一般管理','一般管理'),
                       ('中级管理','中级管理'),('高级管理','高级管理'),('负责人','负责人'),('教师','教师'),
                       ('医生','医生'),('警察','警察'),('退休','退休'))
    SCORING_CHOICE = ((0,'评分未完成'), (1,'评分结果已出'))
    customer_id = models.AutoField(primary_key=True, verbose_name="客户ID")
    customer_name = models.CharField(max_length=20, blank=True, null=True, verbose_name="客户名称")
    idno = models.CharField(max_length=20, blank=True, null=True, verbose_name="身份证号码")
    phone = models.CharField(max_length=20, blank=True, null=True, verbose_name="手机/电话")
    annual_income = models.IntegerField(default=0, verbose_name="年收入")
    apply_quota = models.IntegerField(default=0, verbose_name="申请额度")
    loan_purpose = models.CharField(max_length=50, null=True, verbose_name="借款用途")
    creditcard_quota = models.IntegerField(default=0, verbose_name="信用卡额度")
    education = models.CharField(max_length=10, verbose_name="学历", choices=EDUCATION_CHOICE)
    marriage = models.CharField(max_length=10, default='未婚', verbose_name="婚姻状况", choices=MARRIAGE_CHOICE)
    property = models.CharField(max_length=10,  verbose_name="房产情况", choices=PROPERTY_CHOICE)
    property_location = models.CharField(max_length=100, blank=True, null=True, verbose_name="房产所在地")
    residence_address = models.CharField(max_length=100, blank=True, null=True, verbose_name="户籍地址")
    residence_year = models.CharField(max_length=10, blank=True, null=True, verbose_name="居住年限")
    vehicle = models.CharField(max_length=10, default='0', null=True, verbose_name="有无车产", choices=VEHICLE_CHOICE)
    residential_address = models.CharField(max_length=100, blank=True, null=True, verbose_name="居住地址")
    living_conditions = models.CharField(max_length=20, blank=True, null=True, verbose_name="居住情况")
    company_name = models.CharField(max_length=50, blank=True, null=True, verbose_name="单位名称")
    company_address = models.CharField(max_length=100, blank=True, null=True, verbose_name="单位地址")
    nature = models.CharField(max_length=100, verbose_name="单位性质", choices=NATURE_CHOICE)
    department = models.CharField(max_length=50, blank=True, null=True, verbose_name="部门")
    position = models.CharField(max_length=10, verbose_name="职位", choices=POSITION_CHOICE)
    recruit_time = models.CharField(max_length=50, blank=True, null=True, verbose_name="入职日期")
    insert_date = models.DateTimeField(default=timezone.now(), verbose_name="导入日期")
    scoring_status = models.IntegerField(default=0, verbose_name="评分状态", choices=SCORING_CHOICE)
    create_by = models.ForeignKey(User)
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        self.create_by = user
        if self.customer_name is None:
            self.customer_name = '客户' + self.customer_id
        super(BaseInfo, self).save(force_insert, force_update, using, update_fields)
    def __unicode__(self):
        return self.customer_name
    class Meta:
        managed = True
        db_table = 'base_info'
class Scoring(models.Model):
    sid = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(to=BaseInfo)
    scoring_status = models.IntegerField(default=0, verbose_name="评分状态")
    scoring = models.CharField(max_length=100, verbose_name="评分结果")
    scoring_detail = models.TextField(verbose_name="评分详细情况")
    class Meta:
        managed = True
        db_table = 'scoring'
class BureauLoanDetail(models.Model):
    detail_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(BaseInfo)
    loan_type = models.CharField(max_length=20, null=True,blank=True, verbose_name= '贷款类型')
    account_status = models.CharField(max_length=20, null=True, blank=True, verbose_name= '账户状态')
    service_no = models.CharField(max_length=20, null=True, blank=True, verbose_name='业务号')
    lender = models.CharField(max_length=50, null= True, blank= True, verbose_name='贷款机构')
    guarantee = models.CharField(max_length=20, null=True, blank= True, verbose_name ='担保方式')
    currency = models.CharField(max_length= 20, null=True, blank=True, verbose_name = '币种')
    repayment_fq = models.CharField(max_length=20, null=True, blank=True, verbose_name='还款频率')
    repayment_month = models.CharField(max_length=20, null=True, blank=True, verbose_name= '还款月数')
    release_date = models.DateField(null=True, verbose_name= '发放日期')
    due_date = models.DateField(null=True, verbose_name='到期日期')
    amount = models.FloatField(null=True, verbose_name = '合同金额')
    balance = models.DecimalField(null=True, max_digits=20, decimal_places=2, verbose_name='贷款余额')
    remaining_month = models.IntegerField(null=True, verbose_name='剩余还款月数')
    recent_repayment = models.DateField(null=True, verbose_name= '最近一次实际还款日期')
    repayment_current = models.DecimalField(max_digits=15, decimal_places=2, verbose_name= '本月应还款金额')
    repayment_actual_current = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='本月实际还款金额')
    overdue_times = models.IntegerField(verbose_name='当前逾期期数')
    overdue_amount = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='当前逾期总额')
    overdue_times_cumulate = models.IntegerField(verbose_name='累计逾期次数')
    overdue_times_max = models.IntegerField(verbose_name='最高逾期期数')
    over_31 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='逾期31至60天未归还贷款本金')
    over_61 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='逾期61至90天未归还贷款本金')
    over_91 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='逾期91至180天未归还贷款本金')
    over_180 = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='逾期180天以上未归还贷款本金')
    insert_date = models.DateTimeField(default=timezone.now())
    class Meta:
        managed = True
        db_table = 'BUREAU_LOAN_D'

#人行报告最近24个月贷款每月还款状态记录
class BureauLoanRepayment(models.Model):
    repayment_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(BaseInfo)
    billing_date = models.DateField(verbose_name='结算年月')
    month_no = models.IntegerField()
    status = models.CharField(max_length=2, verbose_name='状态代码')
    insert_date = models.DateTimeField(default=timezone.now())
    class Meta:
        managed = True
        db_table = "BUREAU_LOAN_REPAYMENT"

#人行报告个人住房公积金信息
class BureauPFund(models.Model):
    fund_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(BaseInfo)
    company = models.CharField(max_length=50, verbose_name = '单位名称')
    account_date = models.DateField(verbose_name='开户日期')
    payment_date_b = models.DateField(verbose_name='初缴年月')
    payment_date_e = models.DateField(verbose_name='缴至年月')
    payment_date_l = models.DateField(verbose_name='最近一次交缴日期')
    company_ratio = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='单位缴存比例')
    personal_ratio = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='个人缴存比例')
    amount_monthly = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='月缴存额')
    data_date = models.DateField(verbose_name='信息获取时间')
    insert_date = models.DateTimeField(default=timezone.now())
    class Meta:
        managed = True
        db_table = "BUREAU_P_FUND"

class BaseInfoImporterModel(XLSXImporter):

    class Meta:
        model = BaseInfo
        ignore_first_line = True
        ignore_empty_lines = True
        exclude = ['customer_id', 'insert_date', 'user']

rcweb/importinfo/forms.py
# -*- coding: UTF-8 -*-
__author__ = 'Michael'
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import NON_FIELD_ERRORS
from models import BaseInfo

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.RegexField(label="用户名:", max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text=("**必填. 30 characters or fewer. Letters, digits and "
                    "@/./+/-/_ only."),
        error_messages={
            'invalid': ("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user
class BaseCreateForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'
    class Meta:
        model = BaseInfo
        exclude = ("customer_id", "create_by", "insert_date", "scoring_status")
        help_texts ={
            'customer_name':'申请人姓名',
            'annual_income':'(必填)申请人的年收入单位元',
            'education':'(必填)',
            'property':'(必填)',
            'marriage':'(必填)',
            'position':'(必填)',
            'nature':'(必填)',
            'creditcard_quota':'(必填)',
            }
        widgets = {
            'property_location': forms.TextInput(attrs={'size':50}),
            'company_name':forms.TextInput(attrs={'size':30}),
            'loan_purpose':forms.TextInput(attrs={'size':50}),
            'company_address':forms.TextInput(attrs={'size':50}),
            'residence_year': forms.NumberInput(attrs={'size':20}),
            'residential_address': forms.TextInput(attrs={'size':50}),
            'residence_address': forms.TextInput(attrs={'size':50}),
        }
        error_messages = {'education': {'required': '下面这项内容为必填!'},
                          'loan_purpose': {'required': '下面这项内容为必填!'},
                          'property': {'required': '下面这项内容为必填!'},
                          'nature': {'required': '下面这项内容为必填!'},
                          'position': {'required': '下面这项内容为必填!'},}

rcweb/importinfo/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.utils import timezone
from django import forms
from forms import UserCreateForm
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django import forms
from django.shortcuts import redirect
from models import BaseInfo, BaseInfoImporterModel
from django.contrib.auth.models import User
from data_importer.views import DataImporterForm
from data_importer.tasks import DataImpoterTask
from forms import BaseCreateForm

def register(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/importinfo/")
    else:
        form = UserCreateForm()
    return render_to_response("registration/register.html", {
        'form': form,
    }, context_instance=RequestContext(request))

def index(request):
	return HttpResponse("请输入用户的基本信息")

class import_create_view(DataImporterForm):
    extra_context = {'title': '请导入用户基本信息:',
                         'template_file': 'importinfo/base_info.xlsx'}
    template_name = "importinfo/import.html"
    success_url = '../list_base'
    importer = BaseInfoImporterModel
    def form_valid(self, form, owner=None):
        return super(import_create_view, self).form_valid(form)


class BaseInfoListView(ListView):
    model = BaseInfo
    template_name = 'importinfo/baseinfo_list.html'
    def get_queryset(self):
        return BaseInfo.objects.filter(create_by=self.request.user)
    def get_context_data(self, **kwargs):
        context = super(BaseInfoListView, self).get_context_data(**kwargs)
        return context

class BaseInfoDetailView(DetailView):
    model = BaseInfo
    template_name = 'importinfo/base_detail.html'
    slug_field = 'customer_id'
    slug_url_kwarg = 'cust'
    def get_context_data(self, **kwargs):
        context = super(BaseInfoDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
class BaseInfoCreateView(CreateView):
    form_class = BaseCreateForm
    template_name = 'importinfo/create.html'
    success_url = '/importinfo/list_base/'
    def render_to_response(self, context, **response_kwargs):
        if self.request.user.id is None:
            return redirect('/importinfo/login')
        return super(BaseInfoCreateView, self).render_to_response(context, **response_kwargs)
# Create your views here.

rcweb/importinfo/templates/importinfo/base.html
{% load admin_static %}{% load firstof from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

rcweb/importinfo/templates/importinfo/base_detail.html
<head>
	<title>
请输入您的客户信息
	</title>
	<body>
<h1>{{ object.headline }}</h1>
<p>{{ object.customer_name }}</p>
<p>Reporter: {{ object.reporter }}</p>
<p>Published: {{ object.pub_date|date }}</p>
<p>Date: {{ now|date }}</p>
	</body>
</head>

rcweb/importinfo/templates/importinfo/baseinfo_list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% load importinfo_extras %}
{% block content %}
    <h2>您导入的客户信息</h2>
    <table border="1" width="100%" align="center">
        <tr bgcolor="green">
            {#<td>{{ object_list|verbose_name:'customer_id' }}</td>#}
            <td>{{ object_list|verbose_name:'customer_name' }}</td>
            <td>{{ object_list|verbose_name:'idno' }}</td>
            <td>{{ object_list|verbose_name:'phone' }}</td>
            <td>{{ object_list|verbose_name:'annual_income' }}</td>
            <td>{{ object_list|verbose_name:'apply_quota' }}</td>
            <td>{{ object_list|verbose_name:'loan_purpose' }}</td>
            <td>{{ object_list|verbose_name:'creditcard_quota' }}</td>
            <td>{{ object_list|verbose_name:'education' }}</td>
            <td>{{ object_list|verbose_name:'property' }}</td>
            <td>{{ object_list|verbose_name:'property_location' }}</td>
            <td>{{ object_list|verbose_name:'residential_address' }}</td>
            <td>{{ object_list|verbose_name:'living_conditions' }}</td>
            <td>{{ object_list|verbose_name:'company_name' }}</td>
            <td>{{ object_list|verbose_name:'department' }}</td>
            <td>{{ object_list|verbose_name:'recruit_time' }}</td>
            <td>{{ object_list|verbose_name:'marriage' }}</td>
            <td>{{ object_list|verbose_name:'vehicle' }}</td>
            <td>{{ object_list|verbose_name:'residence_address' }}</td>
            <td>{{ object_list|verbose_name:'residence_year' }}</td>
            <td>{{ object_list|verbose_name:'company_address' }}</td>
            <td>{{ object_list|verbose_name:'nature' }}</td>
            <td>{{ object_list|verbose_name:'position' }}</td>
            <td>操作</td>
            <td>{{ object_list|verbose_name:'scoring_status'}}</td>
        </tr>

        {% for BaseInfo in object_list %}
        <tr>
            {#<td>{{ BaseInfo.customer_id }}</td>#}
            <td>{% if BaseInfo.customer_name != null %}{{BaseInfo.customer_name}}{% else %}客户{{BaseInfo.customer_id}}{% endif %}</td>
            <td>{{ BaseInfo.idno }}</td>
            <td>{{ BaseInfo.phone }}</td>
            <td>{{ BaseInfo.annual_income }}</td>
            <td>{{ BaseInfo.apply_quota }}</td>
            <td>{{ BaseInfo.loan_purpose| default_if_none:"" }}</td>
            <td>{{ BaseInfo.creditcard_quota }}</td>
            <td>{{ BaseInfo.education }}</td>
            <td>{{ BaseInfo.property }}</td>
            <td>{{ BaseInfo.property_location|default_if_none:"" }}</td>
            <td>{{ BaseInfo.residential_address|default_if_none:"" }}</td>
            <td>{{ BaseInfo.living_conditions|default_if_none:"" }}</td>
            <td>{{ BaseInfo.company_name|default_if_none:"" }}</td>
            <td>{{ BaseInfo.department|default_if_none:"" }}</td>
            <td>{{ BaseInfo.recruit_time|default_if_none:"" }}</td>
            <td>{{ BaseInfo.marriage }}</td>
            <td>{{ BaseInfo.vehicle |default_if_none:""}}</td>
            <td>{{ BaseInfo.residence_address|default_if_none:"" }}</td>
            <td>{{ BaseInfo.residence_year|default_if_none:0 }}</td>
            <td>{{ BaseInfo.company_address|default_if_none:"" }}</td>
            <td>{{ BaseInfo.nature|default_if_none:"" }}</td>
            <td>{{ BaseInfo.position }}</td>
            <td><input type="button" value="导入征信信息" onclick="location.href='{% url 'importinfo:detail_base' BaseInfo.customer_id %}'"></td>
            <td>{% if BaseInfo.scoring_status = 0 %}评分未完成{% else %} 评分完成 {% endif%}</td>
        </tr>
        {% endfor %}
    </table >
{% endblock %}
</body>

</html>

rcweb/importinfo/templates/importinfo/create.html
<head>
	<title>
请输入您的客户信息
	</title>
	<body>
		<form action="" method="post">{% csrf_token %}
            <table align="center">{{ form.as_table }}
            <tr><td><input type="submit" value="保存" /></td></tr>
            </table>
		</form>
	</body>
</head>

rcweb/importinfo/templates/importinfo/import.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ title|default:"Example" }}</title>
</head>
<body>
{% comment %}Include this to your upload page template{% endcomment %}
<h1> {{ title }} </h1>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<a href="{{ template_file }}">download template file</a>

<form action="{{ file_upload_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload File" />
</form>
</body>
</html>